languageCode = "en"
languageName = "English"
weight = 1
title = "Priyak Dey"

[params]
  displayName = "EN"
  isoCode = "en"
  rtl = false
  dateFormat = "2 January 2006"
  # logo = "img/2.png"
  # secondaryLogo = "img/1.png"
  description = "Priyak Dey personal website"
  copyright = "&copy; Priyak Dey, _2024_-_2026_"

[params.author]
  name = " Priyak Dey"
  email = "reach@priyakdey.com"
  image = "img/priyakdey.png"
  headline = "Code and Wander: Journeys in Code, Camera, and the Quest for Meaning"
  bio = "Code and Wander: Journeys in Code, Camera, and the Quest for Meaning"
  links = [
    { email = "mailto:reach@priyakdey.com" },
    { github = "https://github.com/priyakdey/" },
    { linkedin = "https://linkedin.com/in/priyakdey/" },
    { stack-overflow = "https://stackoverflow.com/users/10368507/priyak-dey/" },
    { instagram = "https://www.instagram.com/priyak_dey/" },
    { flickr = "https://www.flickr.com/photos/114379474@N04/" },
    { facebook = "https://www.facebook.com/priyak.dey/" },
    { x-twitter = "https://twitter.com/DeyPriyak" },
    { youtube = "https://www.youtube.com/@priyak1991dey" },
]
